services:

  postgres-banking-service:
    image: postgres:18
    container_name: postgres-banking-service-container
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=rafael
      - POSTGRES_DB=agencia
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-audit:
    image: postgres:18
    container_name: postgres-audit-container
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=rafael
      - POSTGRES_DB=audit
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_audit_data:/var/lib/postgresql

  postgres-db:
    image: postgres:18
    container_name: postgres-db-container
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=rafael
      - POSTGRES_DB=agencia
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_db_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_audit_data:
    driver: local
  postgres_db_data:
    driver: local
  rabbitmq_data:
    driver: local