quarkus.http.port=8282

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME:rafael}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD:rafael}
quarkus.datasource.reactive.url = postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5434}/audit


mp.messaging.incoming.notificacoes.connector=smallrye-rabbitmq
mp.messaging.incoming.notificacoes.exchange.type=direct
mp.messaging.incoming.notificacoes.queue.name=notificacao.audit
#mp.messaging.incoming.notificacoes.host=localhost
#mp.messaging.incoming.notificacoes.port=5672

quarkus.devservices.enabled=false